import Foundation

/// A discovery menu entry generated by a source's static or JavaScript `exploreUrl` rule.
public nonisolated struct ExploreMenuItem: Identifiable, Hashable, Sendable {
    public let title: String
    public let url: String?
    public let type: String?
    public let choices: [String]
    public let defaultValue: String?
    public let action: String?

    public init(
        title: String,
        url: String? = nil,
        type: String? = nil,
        choices: [String] = [],
        defaultValue: String? = nil,
        action: String? = nil
    ) {
        self.title = title
        self.url = url
        self.type = type
        self.choices = choices
        self.defaultValue = defaultValue
        self.action = action
    }

    public var id: String {
        "\(title)::\(url ?? "")::\(type ?? "")::\(action ?? "")"
    }

    public var isSelection: Bool {
        type?.lowercased() == "select" && !choices.isEmpty && !(action?.isEmpty ?? true)
    }
}

// MARK: - BrowserRecoveryHeuristics

/// 浏览器恢复判定规则。
///
/// 这是 request runtime 的通用能力，供 `RequestExecutorV2` 和回归测试共享。
/// 它不再属于旧 `WebBook` 编排层，避免 WebView 防护页识别继续散落在业务流程里。
nonisolated enum BrowserRecoveryHeuristics {
    enum RecoveryMode {
        case renderHTML
        case reloadURL
    }

    static func shouldAttemptRecovery(
        statusCode: Int,
        server: String,
        mitigationHeader: String,
        body: String
    ) -> Bool {
        recoveryMode(
            statusCode: statusCode,
            server: server,
            mitigationHeader: mitigationHeader,
            body: body
        ) != nil
    }

    static func recoveryMode(
        statusCode: Int,
        server: String,
        mitigationHeader: String,
        body: String
    ) -> RecoveryMode? {
        let normalizedBody = body.lowercased()
        let normalizedServer = server.lowercased()
        let normalizedMitigationHeader = mitigationHeader.lowercased()

        if isCloudflareChallenge(
            statusCode: statusCode,
            server: normalizedServer,
            mitigationHeader: normalizedMitigationHeader,
            body: normalizedBody
        ) {
            return .renderHTML
        }

        if isScriptRedirectChallenge(body: normalizedBody) {
            return .reloadURL
        }

        return nil
    }

    static func isCloudflareChallenge(
        statusCode: Int,
        server: String,
        mitigationHeader: String,
        body: String
    ) -> Bool {
        let hasChallengeMarkers =
            !mitigationHeader.isEmpty ||
            server.contains("cloudflare") ||
            body.contains("window._cf_chl_opt") ||
            body.contains("challenge-platform") ||
            body.contains("enable javascript and cookies to continue") ||
            body.contains("attention required! | cloudflare") ||
            body.contains("just a moment...")

        guard hasChallengeMarkers else {
            return false
        }

        return statusCode == 403 || statusCode == 429 || statusCode == 503 || !mitigationHeader.isEmpty
    }

    static func isScriptRedirectChallenge(body: String) -> Bool {
        let hasRedirectTitle =
            body.contains("<title>redirecting...</title>") ||
            body.contains("<title>redirecting</title>")
        let hasScriptNavigation =
            body.contains("window.location.replace(") ||
            body.contains("window.location.href") ||
            body.contains("location.reload()") ||
            body.contains("document.getelementbyid(") && body.contains(".click()")
        let hasChallengeRouter =
            body.contains("router.parklogic.com") ||
            body.contains("adblockingdetected") ||
            body.contains("document.write(`<a id=")

        return hasChallengeRouter || (hasRedirectTitle && hasScriptNavigation)
    }
}

// MARK: - LegadoRuntimeConfiguration

/// 书源解析运行时配置。
///
/// SwiftUI / MVVM 层通过 `LegadoBookEngine` 传入策略，不再直接控制底层 transport、
/// WebView、trace 或分页验收细节。
public nonisolated struct LegadoRuntimeConfiguration: Sendable {
    public var maximumRequestTimeout: TimeInterval
    public var allowsWebViewRequests: Bool
    public var allowsAutomaticWebViewRecovery: Bool
    public var allowsThirdPartyTransport: Bool
    public var maximumTocPages: Int
    public var maximumContentPages: Int
    public var defaultCharset: String
    public var enableRuntimeTrace: Bool
    public var compareMode: Bool

    public static let `default` = LegadoRuntimeConfiguration()

    public init(
        maximumRequestTimeout: TimeInterval = 60,
        allowsWebViewRequests: Bool = true,
        allowsAutomaticWebViewRecovery: Bool = true,
        allowsThirdPartyTransport: Bool = true,
        maximumTocPages: Int = 20,
        maximumContentPages: Int = 20,
        defaultCharset: String = "UTF-8",
        enableRuntimeTrace: Bool = false,
        compareMode: Bool = false
    ) {
        self.maximumRequestTimeout = max(1, maximumRequestTimeout)
        self.allowsWebViewRequests = allowsWebViewRequests
        self.allowsAutomaticWebViewRecovery = allowsAutomaticWebViewRecovery
        self.allowsThirdPartyTransport = allowsThirdPartyTransport
        self.maximumTocPages = max(1, maximumTocPages)
        self.maximumContentPages = max(1, maximumContentPages)
        self.defaultCharset = defaultCharset
        self.enableRuntimeTrace = enableRuntimeTrace
        self.compareMode = compareMode
    }
}

// MARK: - LegadoBookEngine

/// 书源解析正式 facade。
///
/// `LegadoBookEngine` 是 ViewModel / service 层面向解析内核的唯一稳定入口。
/// 内部执行链路固定走 Android 对齐式 V2 runtime：
/// `AnalyzeUrlV2 -> RequestExecutorV2 -> StageRuntimeFactoryV2 -> RuleRuntimeV2 -> *ParserV2`。
public nonisolated final class LegadoBookEngine {
    public let source: BookSource
    public let configuration: LegadoRuntimeConfiguration

    private let runtime: WebBookV2
    private let runtimeTrace: RuntimeTraceV2?
    private let legacyRequestTraceCollector: LegadoRequestTraceCollector?

    public init(
        source: BookSource,
        configuration: LegadoRuntimeConfiguration = .default,
        legacyRequestTraceCollector: LegadoRequestTraceCollector? = nil
    ) {
        self.source = source
        self.configuration = configuration
        self.legacyRequestTraceCollector = legacyRequestTraceCollector

        let trace = (configuration.enableRuntimeTrace || legacyRequestTraceCollector != nil) ? RuntimeTraceV2() : nil
        self.runtimeTrace = trace
        self.runtime = WebBookV2(
            bookSource: source,
            maximumRequestTimeout: configuration.maximumRequestTimeout,
            allowsWebViewRequests: configuration.allowsWebViewRequests,
            allowsAutomaticWebViewRecovery: configuration.allowsAutomaticWebViewRecovery,
            runtimeTrace: trace
        )
    }

    // Engine 只封装 V2 runtime 与 trace 句柄，不需要 actor/executor 参与析构。
    // compare 长跑中若走默认隔离析构，会在 Swift 当前运行时下触发 TaskLocal bad-free。

    public nonisolated func search(
        keyword: String,
        page: Int = 1,
        maximumResults: Int? = nil
    ) async throws -> [SearchBook] {
        defer { flushTraceToLegacyCollector() }
        return try await runtime.searchBook(keyword: keyword, page: page, maximumResults: maximumResults)
    }

    public nonisolated func fetchBookInfo(
        bookUrl: String,
        baseUrl: String? = nil,
        cachedInfoHtml: String? = nil,
        variables: [String: String] = [:],
        sourceVariables: [String: String] = [:],
        bookVariables: [String: String] = [:],
        name: String = "",
        author: String = "",
        kind: String = ""
    ) async throws -> BookDetail {
        defer { flushTraceToLegacyCollector() }
        return try await runtime.getBookInfo(
            bookUrl: bookUrl,
            baseUrl: baseUrl,
            cachedInfoHtml: cachedInfoHtml,
            variables: variables,
            sourceVariables: sourceVariables,
            bookVariables: bookVariables,
            name: name,
            author: author,
            kind: kind
        )
    }

    public nonisolated func fetchToc(
        tocUrl: String,
        bookUrl: String,
        maxPages: Int? = nil,
        cachedTocHtml: String? = nil,
        variables: [String: String] = [:],
        sourceVariables: [String: String] = [:],
        bookVariables: [String: String] = [:],
        name: String = "",
        author: String = "",
        kind: String = "",
        mode: WebBook.TocFetchMode = .full
    ) async throws -> [BookChapter] {
        defer { flushTraceToLegacyCollector() }
        return try await runtime.getTocList(
            tocUrl: tocUrl,
            bookUrl: bookUrl,
            maxPages: maxPages ?? configuration.maximumTocPages,
            cachedTocHtml: cachedTocHtml,
            variables: variables,
            sourceVariables: sourceVariables,
            bookVariables: bookVariables,
            name: name,
            author: author,
            kind: kind,
            fetchMode: mode
        )
    }

    public nonisolated func fetchContent(
        chapter: BookChapter,
        maxPages: Int? = nil,
        nextChapterUrl: String? = nil,
        variables: [String: String] = [:],
        mode: WebBook.ContentFetchMode = .full
    ) async throws -> ChapterContent {
        defer { flushTraceToLegacyCollector() }
        return try await runtime.getContent(
            chapter: chapter,
            maxPages: maxPages ?? configuration.maximumContentPages,
            nextChapterUrl: nextChapterUrl,
            variables: variables,
            fetchMode: mode
        )
    }

    public func explore(url: String, page: Int = 1) async throws -> [SearchBook] {
        defer { flushTraceToLegacyCollector() }
        return try await runtime.getExploreList(url: url, page: page)
    }

    public func exploreCategories() -> [(name: String, url: String)] {
        runtime.getExploreCategories()
    }

    public func exploreMenu() -> [ExploreMenuItem] {
        runtime.getExploreMenu()
    }

    public func applyExploreMenuAction(
        _ action: String,
        infoMap: [String: String]
    ) throws {
        try runtime.applyExploreMenuAction(action, infoMap: infoMap)
    }

    public func shutdown() {
        runtime.shutdown()
        flushTraceToLegacyCollector()
    }

    private func flushTraceToLegacyCollector() {
        guard let legacyRequestTraceCollector, let runtimeTrace else { return }
        let descriptors = runtimeTrace.drain()
        guard !descriptors.isEmpty else { return }
        descriptors.forEach { legacyRequestTraceCollector.append($0.legacyDescriptor) }
    }
}

// MARK: - WebBook

/// 兼容旧调用点的书源解析入口。
///
/// 该类现在只保留 public API 和少量测试辅助方法，真实解析已经迁到 `LegadoBookEngine`。
/// 这样 UI / 测试 / compare 不需要同时大改，执行路径则一次切到 Android 对齐式 V2 runtime。
public nonisolated final class WebBook {
    public enum TocFetchMode: Sendable {
        case full
        case validation(minimumChapterCount: Int = 2, minimumUsableChapterCount: Int = 1)
    }

    public enum ContentFetchMode: Sendable {
        case full
        case validation(maximumPages: Int = 1, minimumCharacterCount: Int = 1)
    }

    public let bookSource: BookSource

    private let engine: LegadoBookEngine

    public init(
        bookSource: BookSource,
        maximumRequestTimeout: TimeInterval = 60,
        allowsWebViewRequests: Bool = true,
        allowsAutomaticWebViewRecovery: Bool = true,
        requestTraceCollector: LegadoRequestTraceCollector? = nil
    ) {
        self.bookSource = bookSource
        self.engine = LegadoBookEngine(
            source: bookSource,
            configuration: LegadoRuntimeConfiguration(
                maximumRequestTimeout: maximumRequestTimeout,
                allowsWebViewRequests: allowsWebViewRequests,
                allowsAutomaticWebViewRecovery: allowsAutomaticWebViewRecovery,
                maximumTocPages: 20,
                maximumContentPages: 10,
                enableRuntimeTrace: requestTraceCollector != nil,
                compareMode: !allowsWebViewRequests
            ),
            legacyRequestTraceCollector: requestTraceCollector
        )
    }


    public func shutdown() {
        engine.shutdown()
    }

    public nonisolated func searchBook(
        keyword: String,
        page: Int = 1,
        maximumResults: Int? = nil
    ) async throws -> [SearchBook] {
        try await engine.search(keyword: keyword, page: page, maximumResults: maximumResults)
    }

    public nonisolated func getBookInfo(
        bookUrl: String,
        baseUrl: String? = nil,
        cachedInfoHtml: String? = nil,
        variables: [String: String] = [:],
        sourceVariables: [String: String] = [:],
        bookVariables: [String: String] = [:],
        name: String = "",
        author: String = "",
        kind: String = ""
    ) async throws -> BookDetail {
        try await engine.fetchBookInfo(
            bookUrl: bookUrl,
            baseUrl: baseUrl,
            cachedInfoHtml: cachedInfoHtml,
            variables: variables,
            sourceVariables: sourceVariables,
            bookVariables: bookVariables,
            name: name,
            author: author,
            kind: kind
        )
    }

    public nonisolated func getTocList(
        tocUrl: String,
        bookUrl: String,
        maxPages: Int = 20,
        cachedTocHtml: String? = nil,
        variables: [String: String] = [:],
        sourceVariables: [String: String] = [:],
        bookVariables: [String: String] = [:],
        name: String = "",
        author: String = "",
        kind: String = "",
        fetchMode: TocFetchMode = .full
    ) async throws -> [BookChapter] {
        try await engine.fetchToc(
            tocUrl: tocUrl,
            bookUrl: bookUrl,
            maxPages: maxPages,
            cachedTocHtml: cachedTocHtml,
            variables: variables,
            sourceVariables: sourceVariables,
            bookVariables: bookVariables,
            name: name,
            author: author,
            kind: kind,
            mode: fetchMode
        )
    }

    public nonisolated func getContent(
        chapter: BookChapter,
        maxPages: Int = 10,
        nextChapterUrl: String? = nil,
        variables: [String: String] = [:],
        fetchMode: ContentFetchMode = .full
    ) async throws -> ChapterContent {
        try await engine.fetchContent(
            chapter: chapter,
            maxPages: maxPages,
            nextChapterUrl: nextChapterUrl,
            variables: variables,
            mode: fetchMode
        )
    }

    public func getExploreCategories() -> [(name: String, url: String)] {
        engine.exploreCategories()
    }

    public func getExploreMenu() -> [ExploreMenuItem] {
        engine.exploreMenu()
    }

    public func applyExploreMenuAction(
        _ action: String,
        infoMap: [String: String]
    ) throws {
        try engine.applyExploreMenuAction(action, infoMap: infoMap)
    }

    public func getExploreList(url: String, page: Int = 1) async throws -> [SearchBook] {
        try await engine.explore(url: url, page: page)
    }

    func isUsableChapterReference(_ chapter: BookChapter, pageURL: String, bookUrl: String) -> Bool {
        TocReferenceHeuristics.isUsableChapterReference(chapter, pageURL: pageURL, bookUrl: bookUrl)
    }
}

// MARK: - TocReferenceHeuristics

enum TocReferenceHeuristics {
    static func isUsableChapterReference(_ chapter: BookChapter, pageURL: String, bookUrl: String) -> Bool {
        guard !chapter.isVolume else { return false }

        let trimmed = chapter.url.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty {
            if trimmed.hasPrefix("javascript:") {
                return false
            }
            if !trimmed.contains("://") && !trimmed.hasPrefix("/") && trimmed.contains("#") {
                return false
            }
            if !urlsEquivalent(trimmed, pageURL) && !urlsEquivalent(trimmed, bookUrl) {
                return true
            }
            if looksLikeChapterPath(trimmed, pageURL: pageURL, bookUrl: bookUrl) {
                return true
            }
        }

        return hasDistinctChapterContext(chapter)
    }

    static func isMeaningfulTocPage(_ chapters: [BookChapter], pageURL: String, bookUrl: String) -> Bool {
        guard !chapters.isEmpty else { return false }
        let usableCount = chapters.filter {
            isUsableChapterReference($0, pageURL: pageURL, bookUrl: bookUrl)
        }.count
        if chapters.count == 1 {
            return usableCount == 1
        }
        return usableCount > 0
    }

    private static func hasDistinctChapterContext(_ chapter: BookChapter) -> Bool {
        if !chapter.chapterVariables.isEmpty {
            return true
        }

        for (key, value) in chapter.variables where !value.isEmpty {
            if chapter.bookVariables[key] != value || chapter.sourceVariables[key] != value {
                return true
            }
        }

        return false
    }

    private static func urlsEquivalent(_ lhs: String, _ rhs: String) -> Bool {
        normalizedURLIdentity(lhs) == normalizedURLIdentity(rhs)
    }

    private static func normalizedURLIdentity(_ value: String) -> String {
        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return "" }
        guard let components = URLComponents(string: trimmed) else {
            return trimmed
        }

        var normalized = components
        normalized.scheme = normalized.scheme?.lowercased()
        normalized.host = normalized.host?.lowercased()
        return normalized.string ?? trimmed
    }

    private static func looksLikeChapterPath(_ candidate: String, pageURL: String, bookUrl: String) -> Bool {
        let trimmed = candidate.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return false }
        guard !trimmed.hasPrefix("javascript:") else { return false }
        guard !trimmed.hasPrefix("#") else { return false }
        guard trimmed != "/" else { return false }

        if trimmed.hasPrefix("/") || trimmed.hasPrefix("./") || trimmed.hasPrefix("../") {
            return true
        }

        if trimmed.contains("://") {
            return false
        }

        let pagePath = URL(string: pageURL)?.path ?? ""
        let bookPath = URL(string: bookUrl)?.path ?? ""
        if pagePath.hasSuffix(trimmed) || bookPath.hasSuffix(trimmed) {
            return false
        }

        let looksLikeHTML = trimmed.contains(".html") || trimmed.contains(".htm") || trimmed.contains(".json")
        let looksLikeNumberedPath = trimmed.range(of: #"\d"#, options: .regularExpression) != nil
        return looksLikeHTML || looksLikeNumberedPath
    }
}

private extension LegadoRequestDescriptorV2 {
    var legacyDescriptor: LegadoRequestDescriptor {
        LegadoRequestDescriptor(
            resolvedURL: resolvedURL,
            method: method,
            headerKeys: headerKeys,
            originalRulePreview: originalRulePreview,
            bodyLength: bodyLength,
            bodyPreview: bodyPreview,
            bodyHash: bodyHash,
            charset: charset,
            webView: webView,
            webJs: webJs,
            sourceRegex: sourceRegex,
            retryCount: retryCount,
            responseType: responseType,
            cookieJarEnabled: cookieJarEnabled,
            timeoutSeconds: timeoutSeconds,
            followRedirects: followRedirects,
            transportPreference: transportPreference
        )
    }
}
